### ISSUE TITLE
Check if we can use Webtorrent

### ISSUE THREAD

**Issue by TriPSs** [pct-org/native-app#32]
https://github.com/webtorrent/webtorrent

**Comment by MrRory** [comment]
Would require some WebRTC module, like https://github.com/oney/react-native-webrtc, to make it hybrid. But I don't really see why it won't work since webtorrent is plain JS. Might get harder once you want background support though I think.

**Comment by team-pct** [comment]
https://github.com/dbrowne24/webtorrent-react maybe for reference

**Comment by TriPSs** [comment]
@MrRory I got it working with React Native Webrtc but the only problem i have now is that `simple-peer` can't connect to the peers, it keeps throwing the error ice connection failed.

**Comment by TriPSs** [comment]
Commited everything to `feature/webtorrent` and created a issue at [simple-peer](https://github.com/simple-peer/issues/445) and [webtorrent](https://github.com/webtorrent/webtorrent/issues/1590)
